### ISSUE TITLE
FE and BE: Create Project Board Labels

### ISSUE THREAD

**Issue by Yesi-MC** [penpost/penpost-api#5]
For both FE and BE Repos, take some time to create labels.
Some Ideas for labels below; 

chore
backend
frontend 
bug 
phase1
phase2
phase3 
documentation
spike 
deployment 
testing 
extension
refactor

**Comment by gaj23** [comment]
Front-end Labels have been edited to match this! 
Additionally, labels have been added to as many issues as possible. There are several issues that I didn't have access to change, though. @Yesi-MC , I'm not sure if you have only permission to change those?

**Comment by Yesi-MC** [comment]
@gaj23 Yes, I have access to the create the labels for the BE repo. I'll go ahead and create those on my end.
